project_id = "jpxyczlocqmfumkakdyx"

[functions.send-notifications]
enabled = true
verify_jwt = false

[functions.send-web-push]
enabled = true
verify_jwt = false

[functions.generate-parsha-content]
enabled = true
verify_jwt = false