// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpxyczlocqmfumkakdyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpweHljemxvY3FtZnVta2FrZHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NDkzNTYsImV4cCI6MjA3NTMyNTM1Nn0.kfkSh0E57bj6DtOmkkDl3Ww-6MSkIVx4CDHDcFnx1FQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});